### ISSUE TITLE
VAT amount is not added to the order total

### ISSUE THREAD

**Issue by bradydan** [strangerstudios/pmpro-vat-tax#11]
The new .4 VAT plugin is not adding the VAT amount to the order total.

Users can enter VAT details, or not, and the base price (pre-tax) is not changed

This is how the plugin should work, as far as I can see:

-  If the VAT add-on is installed AND I set my EU VAT Seller Country ti ‘United Kingdom’, the default VAT rate should automatically be set to 20%. (ie 20% is added to all the prices)
-  If a member enters their EU country, the VAT rate should change to the country-specific VAT rate percentage (and the order total updated)
-  If a member enters their EU VAT code, then the VAT should be removed from the order total

In its current state, this plugin is not usable.

**Comment by bradydan** [comment]
After making the [GB to UK change](https://github.com/strangerstudios/pmpro-vat-tax/pull/12#event-1024003436), the VAT still does not appear as an extra item in the order.

- When the seller country is set to UK, and the customer’s billing address country is also set to UK, the EU VAT section doesn’t appear at all. 
- VAT needs to be charged to customers in the seller’s own country, not just other EU countries.
- Why ask the customer to set the EU country at all? The VAT plugin should pick up the billing address country already entered in the payment details, and set the VAT rate based on that country.

I assume the changes are not being tested thoroughly. I am going to detail the steps here required to test this VAT add-on, which I hope you can pass on to the developer:

**Scenario 1 (UK seller and UK member):**

1. Set the seller country to United kingdom
2.  Go to checkout as a member with billing country = United Kingdom
3.  Customer should be charged 20% VAT on top of their selected member level price. Customer should be able to check out with this tax added and the updated total visible in the checkout.
4.  Customer should have the option to enter a VAT number, which sets the VAT rate to 0%, and in this instance checkout with no tax added

**Scenario 2 (UK seller and Danish member):**

1.  Set the seller country to United kingdom
2.  Go to checkout as a member with billing country = Denmark
3.  Customer should be charged 25% VAT on top of their selected member level price. Customer should be able to check out with this tax added and the updated total visible in the checkout.
4.  Customer should have the option to enter a valid VAT number, which sets the VAT rate to 0%, and checkout without the tax added.

**Scenario 3 (UK seller and USA member):**

1.  Set the seller country to United kingdom
2.  Go to checkout as a member with a billing country = United States
3.  US customer should be charged no VAT on top of their selected member level price.
4.  Customer should NOT have the option to enter a valid VAT number

**The basic logic for the VAT add-on should be this:**

1.  Check the seller’s country
2.  If the seller country is set to an EU country, the VAT plugin should run, else ignore the VAT plugin
3.  Check the customer’s billing address country.
4.  If the customer’s billing country is an EU country, add an order line item of VAT at that billing country’s rate (eg UK = additional 20%, Denmark = additional 25%, etc).
5.  If the customer’s billing country is an EU country, display the optional field where a customer can enter their own EU VAT number.
6.  If a VAT number is entered, validate it. If it validates, remove the order line for VAT (or set to 0%), else if the VAT number is not entered, continue to charge the VAT at the billing country rate

**Comment by strangerstudios** [comment]
v.4.1 fixes an issue where we were handling the ISO/VAT codes for the UK (and Greece) incorrectly. This should have fixed your issue. Let me know if you are still running into problems here.

**Comment by bradydan** [comment]
I'll just copy this again from an earlier comment (third time):

> the VAT still does not appear as an extra item in the order

No VAT is charged. I think I need a refund …

**Comment by strangerstudios** [comment]
> I think I need a refund … 

Email us and we'll process it ASAP.

**Comment by strangerstudios** [comment]
@bradydan I'll need more specifics about your setup and how you are checking out (exactly which gateway, countries, level settings) to test it. We could do a better job of it, but the VAT amount is showing up as a separate amount on the confirmation and invoice pages as well as the orders export.

Since the original lists of tests just passed for me, I'm going to close this issue. But please open a new one if a specific scenario is breaking for you.

Thanks again for the help and patience.
