### ISSUE TITLE
Enhancement: Better handling of VAT number

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-vat-tax#33]
As per this topic: https://www.paidmembershipspro.com/forums/topic/vat-number-on-checkout-and-also-wrong-on-invoices/

An EU VAT number consists of a country prefix such as NL or DE and then a 8 digit number — like: DE12345678

On the checkout page, only the 8 digit code is accepted without the country prefix. – 12345678. We also only validate the number, without the prefix.

Therefore, PMPRO prints a wrong VAT number of the client on the invoice as the country prefix is missing.

**Comment by MaryOJob** [comment]
Same request here: https://www.paidmembershipspro.com/forums/topic/vat-number-format/ (Moderators Only)

**Comment by MaryOJob** [comment]
Similar (Moderators Only): #477741
