### ISSUE TITLE
Portuguese VAT number fails to validate

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-vat-tax#50]
Entering a valid Portuguese VAT number returns invalid. It seems some VAT validations return true while mostly returning false.

Ticket Reference: #377166

**Comment by michaelbeil** [comment]
A customer is experiencing this error with a German VAT number.
>in our checkout the VAT number validation does not work. It’s showing the error: “Die Umsatzsteuer-Identifikationsnummer wurde nicht verifiziert. Bitte versuche es erneut.”
Translation to english means: “The VAT number could not be verified. Please try again.”

**Comment by MaryOJob** [comment]
Similar (Moderators Only): #477741

**Comment by andrewlimaza** [comment]
This PR may fix things - https://github.com/strangerstudios/pmpro-vat-tax/pull/61
