### ISSUE TITLE
Detect if the VAT Number Entered Contains the Country ISO Code

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-vat-tax#59]
There's cases where a member will enter a full VAT number including country code which results in the validation failing as we prepend the country code to the VAT number before validation.

We should rather check if the country code is present, then use it as is, otherwise prepend it to the VAT number where necessary based on the country selected.

**Comment by andrewlimaza** [comment]
Related: https://github.com/strangerstudios/pmpro-vat-tax/issues/33
